apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ioteam-mohan1
  description: Sample iot app
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  owner: group:default/ioteam
  lifecycle: experimental
